// <auto-generated />
namespace Kosmos.Extract.Tripadvisor.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_depth__ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_depth__));
        
        string IMigrationMetadata.Id
        {
            get { return "201612130228345_add_depth__"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
